spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pomegranate?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    #      spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect